using System.Data;
using Microsoft.EntityFrameworkCore;

namespace StarterApp.Database.Data;

public static class LegacySchemaRepair
{
    private const string ProductVersion = "9.0.6";
    private const string InitialMigrationId = "20260210141124_InitialCreate";
    private const string AddItemsMigrationId = "20260317193000_AddItemsAndRefreshTokens";
    private const string AddRentalRequestsMigrationId = "20260326161019_AddRentalRequests";

    public static async Task NormalizeAsync(AppDbContext db, CancellationToken cancellationToken = default)
    {
        await db.Database.OpenConnectionAsync(cancellationToken);
        try
        {
            await ExecuteNonQueryAsync(db, @"
CREATE TABLE IF NOT EXISTS ""__EFMigrationsHistory"" (
    ""MigrationId"" character varying(150) NOT NULL,
    ""ProductVersion"" character varying(32) NOT NULL,
    CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY (""MigrationId"")
);", cancellationToken);

            if (await TableExistsAsync(db, "users", cancellationToken)
                && await TableExistsAsync(db, "role", cancellationToken)
                && await TableExistsAsync(db, "user_role", cancellationToken))
            {
                await EnsureHistoryEntryAsync(db, InitialMigrationId, cancellationToken);
            }

            var hasRefreshToken = await TableExistsAsync(db, "refresh_token", cancellationToken);
            var hasItem = await TableExistsAsync(db, "item", cancellationToken);

            if (hasRefreshToken && !await HistoryEntryExistsAsync(db, AddItemsMigrationId, cancellationToken))
            {
                if (!hasItem)
                {
                    await ExecuteNonQueryAsync(db, @"
CREATE TABLE IF NOT EXISTS item (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ""Title"" character varying(150) NOT NULL,
    ""Description"" character varying(2000) NOT NULL,
    ""DailyRate"" numeric(10,2) NOT NULL,
    ""Category"" character varying(100) NOT NULL,
    ""Location"" character varying(200) NOT NULL,
    ""Latitude"" double precision NULL,
    ""Longitude"" double precision NULL,
    ""OwnerUserId"" integer NOT NULL,
    ""CreatedAtUtc"" timestamp with time zone NOT NULL,
    ""UpdatedAtUtc"" timestamp with time zone NOT NULL,
    ""IsActive"" boolean NOT NULL,
    CONSTRAINT ""PK_item"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_item_users_OwnerUserId"" FOREIGN KEY (""OwnerUserId"") REFERENCES users (""Id"") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ""IX_item_OwnerUserId"" ON item (""OwnerUserId"");
", cancellationToken);
                }

                await EnsureHistoryEntryAsync(db, AddItemsMigrationId, cancellationToken);
            }

            if (await TableExistsAsync(db, "rental_request", cancellationToken))
            {
                await EnsureHistoryEntryAsync(db, AddRentalRequestsMigrationId, cancellationToken);
            }
        }
        finally
        {
            await db.Database.CloseConnectionAsync();
        }
    }

    private static async Task<bool> TableExistsAsync(AppDbContext db, string tableName, CancellationToken cancellationToken)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        command.CommandText = @"
SELECT EXISTS (
    SELECT 1
    FROM pg_tables
    WHERE schemaname = current_schema()
      AND tablename = @tableName
);";

        var parameter = command.CreateParameter();
        parameter.ParameterName = "tableName";
        parameter.DbType = DbType.String;
        parameter.Value = tableName;
        command.Parameters.Add(parameter);

        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is true || result is bool boolResult && boolResult;
    }

    private static async Task<bool> HistoryEntryExistsAsync(AppDbContext db, string migrationId, CancellationToken cancellationToken)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        command.CommandText = @"
SELECT EXISTS (
    SELECT 1
    FROM ""__EFMigrationsHistory""
    WHERE ""MigrationId"" = @migrationId
);";

        var parameter = command.CreateParameter();
        parameter.ParameterName = "migrationId";
        parameter.DbType = DbType.String;
        parameter.Value = migrationId;
        command.Parameters.Add(parameter);

        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is true || result is bool boolResult && boolResult;
    }

    private static async Task EnsureHistoryEntryAsync(AppDbContext db, string migrationId, CancellationToken cancellationToken)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        command.CommandText = @"
INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
VALUES (@migrationId, @productVersion)
ON CONFLICT (""MigrationId"") DO NOTHING;";

        var migrationParameter = command.CreateParameter();
        migrationParameter.ParameterName = "migrationId";
        migrationParameter.DbType = DbType.String;
        migrationParameter.Value = migrationId;
        command.Parameters.Add(migrationParameter);

        var productVersionParameter = command.CreateParameter();
        productVersionParameter.ParameterName = "productVersion";
        productVersionParameter.DbType = DbType.String;
        productVersionParameter.Value = ProductVersion;
        command.Parameters.Add(productVersionParameter);

        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task ExecuteNonQueryAsync(AppDbContext db, string sql, CancellationToken cancellationToken)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}