services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      CONNECTION_STRING: Host=db;Port=5432;Username=dev_user;Password=dev_password;Database=devdb
      Jwt__Issuer: StarterApp.Api
      Jwt__Audience: StarterApp.Client
      Jwt__SigningKey: ffetr45t453tegv5yhgrddb#oH.t065z=5wU#4t\kccJ5#vH#83n5
      Jwt__AccessTokenMinutes: 15
      Jwt__RefreshTokenDays: 7
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"  # maps host to container
    environment:
      ADB_SERVER_SOCKET: tcp:127.0.0.1:5037
      CONNECTION_STRING: Host=db;Port=5432;Username=dev_user;Password=dev_password;Database=devdb
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: devdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
