services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # maps host to container
    environment:
      ADB_SERVER_SOCKET: tcp:host.docker.internal:5037  # make sure container sees host ADB
      CONNECTION_STRING: Host=db;Port=5432;Username=dev_user;Password=dev_password;Database=devdb
      AUTH_API_BASE_URL: http://host.docker.internal:8080
    depends_on:
      db:
        condition: service_healthy

  api:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /workspace
    command: >-
      sh -c "dotnet restore StarterApp.Api/StarterApp.Api.csproj &&
      dotnet run --project StarterApp.Api/StarterApp.Api.csproj --urls http://0.0.0.0:8080"
    volumes:
      - .:/workspace:cached
    environment:
      CONNECTION_STRING: Host=db;Port=5432;Username=dev_user;Password=dev_password;Database=devdb
      Jwt__Issuer: StarterApp.Api
      Jwt__Audience: StarterApp.Client
      Jwt__SigningKey: dev-signing-key-change-this-in-real-environments-123456
      Jwt__AccessTokenMinutes: 15
      Jwt__RefreshTokenDays: 7
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: devdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
