using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace StarterApp.Database.Migrations
{
    public partial class AddItemsAndRefreshTokens : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS item (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ""Title"" character varying(150) NOT NULL,
    ""Description"" character varying(2000) NOT NULL,
    ""DailyRate"" numeric(10,2) NOT NULL,
    ""Category"" character varying(100) NOT NULL,
    ""Location"" character varying(200) NOT NULL,
    ""Latitude"" double precision NULL,
    ""Longitude"" double precision NULL,
    ""OwnerUserId"" integer NOT NULL,
    ""CreatedAtUtc"" timestamp with time zone NOT NULL,
    ""UpdatedAtUtc"" timestamp with time zone NOT NULL,
    ""IsActive"" boolean NOT NULL,
    CONSTRAINT ""PK_item"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_item_users_OwnerUserId"" FOREIGN KEY (""OwnerUserId"") REFERENCES users (""Id"") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ""IX_item_OwnerUserId"" ON item (""OwnerUserId"");
");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS refresh_token (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ""UserId"" integer NOT NULL,
    ""TokenHash"" character varying(128) NOT NULL,
    ""CreatedAtUtc"" timestamp with time zone NOT NULL,
    ""ExpiresAtUtc"" timestamp with time zone NOT NULL,
    ""IsRevoked"" boolean NOT NULL,
    ""RevokedAtUtc"" timestamp with time zone NULL,
    CONSTRAINT ""PK_refresh_token"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_refresh_token_users_UserId"" FOREIGN KEY (""UserId"") REFERENCES users (""Id"") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_refresh_token_TokenHash"" ON refresh_token (""TokenHash"");
CREATE INDEX IF NOT EXISTS ""IX_refresh_token_UserId"" ON refresh_token (""UserId"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS item;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS refresh_token;");
        }
    }
}
